# Generated by Django 2.1.3 on 2018-11-30 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('pic', models.CharField(max_length=2500)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SodaMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sodaMachine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.SodaMachine'),
        ),
        migrations.AddField(
            model_name='coin',
            name='sodaMachine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.SodaMachine'),
        ),
        migrations.AddField(
            model_name='coin',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.Value'),
        ),
    ]
