# Generated by Django 2.1.3 on 2018-11-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
