# Generated by Django 2.1.3 on 2018-11-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20181130_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=5),
        ),
    ]
